name: auslogicstest
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  logger: ^0.9.1
  get: ^2.12.6
  moor_flutter: ^3.0.0
  flutter_bloc: ^4.0.1
  equatable: ^1.2.0
  meta: ^1.1.8
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
